name: Client

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/DzoukrCz.Client/**'
      - 'src/DzoukrCz.Shared/**'
      - '.github/workflows/Client.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet run Publish

      - name: Publish Client
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: publish/app/client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: client
          path: client
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: client
          CLEAN: true
