name: Web

on:
  push:
    branches: [ master ]
    paths:
      - 'src/DzoukrCz.Web/**'
      - '.github/workflows/Web.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn version
        run: corepack prepare yarn@4.9.4 --activate

      - name: Install dependencies
        working-directory: src/DzoukrCz.Web
        run: yarn install --immutable

      - name: Build Next.js app
        working-directory: src/DzoukrCz.Web
        run: yarn build

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          skip_app_build: true
          action: 'upload'
          app_location: 'src/DzoukrCz.Web/out'
          output_location: ''