name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/DzoukrCz.Web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'src/DzoukrCz.Web/yarn.lock'

      - name: Install dependencies
        working-directory: src/DzoukrCz.Web
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        working-directory: src/DzoukrCz.Web
        run: yarn build

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          skip_app_build: true
          action: 'upload'
          app_location: 'src/DzoukrCz.Web/out'
          output_location: ''